collections:
  - name: 'gallery'
    label: 'Galleria'
    delete: false # Prevents deletion since it's a single-type collection
    editor:
      preview: false
    files:
      - name: 'gallery'
        label: 'Galleria'
        file: 'content/gallery.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string' }
          - { name: 'content', label: 'Content', widget: 'markdown' }
          - name: 'images'
            label: 'Images'
            widget: 'list'
            summary: '{{fields.image}}'
            field:
              name: 'image'
              label: 'Image'
              widget: 'image'
